### ISSUE TITLE
Apply a default pagination

### ISSUE THREAD

**Issue by martn001** [kingscode/vuetify-resource#57]
You're unable to give your own default pagination. It always is 10, 25 and 100 rows. You should be able to customize the pagination for creating different scenarios.

![current-display-of-situation](https://user-images.githubusercontent.com/8685175/61780932-bb2e0100-ae03-11e9-8b5c-57b61df1e317.PNG)

**Comment by ricardovanlaarhoven** [comment]
We could use the `rows-per-page-items` prop from the vuetify's data-table
i don't know if it's possible to select which one is default, i think it's always the first one
